import discord
from discord.ext import commands
import os
import asyncio
from gtts import gTTS
import re
from keep_alive import keep_alive
from dotenv import load_dotenv

# Carrega variáveis locais se houver um arquivo .env
load_dotenv()

TOKEN = os.getenv('TOKEN')

# NOVA ABORDAGEM: Sem bloco try/except para não dar erro de sintaxe no celular!
_canal_env = os.getenv('CANAL_TEXTO_ID', '0')
CANAL_TEXTO_ID = int(_canal_env) if _canal_env.isdigit() else 0

# Configuração de Intents
intents = discord.Intents.default()
intents.message_content = True
intents.voice_states = True

bot = commands.Bot(command_prefix='!', intents=intents)

# Classe para gerenciar o estado da fila
class GuildState:
    def __init__(self):
            self.queue = asyncio.Queue()
                    self.is_playing = False
                            self.afk_task = None

                            guild_states = {}

                            def get_state(guild_id):
                                if guild_id not in guild_states:
                                        guild_states[guild_id] = GuildState()
                                            return guild_states[guild_id]

                                            async def play_next(guild, voice_client):
                                                state = get_state(guild.id)
                                                    
                                                        if state.queue.empty():
                                                                state.is_playing = False
                                                                        return

                                                                            state.is_playing = True
                                                                                text, message_id = await state.queue.get()
                                                                                    
                                                                                        file_name = f"tts_{guild.id}_{message_id}.mp3"
                                                                                            
                                                                                                try:
                                                                                                        tts = gTTS(text=text, lang='pt')
                                                                                                                tts.save(file_name)
                                                                                                                        
                                                                                                                                def after_playing(error):
                                                                                                                                            if error:
                                                                                                                                                            print(f"Erro no playback: {error}")
                                                                                                                                                                        try:
                                                                                                                                                                                        if os.path.exists(file_name):
                                                                                                                                                                                                            os.remove(file_name)
                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                        pass
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                coro = play_next(guild, voice_client)
                                                                                                                                                                                                                                                                            asyncio.run_coroutine_threadsafe(coro, bot.loop)

                                                                                                                                                                                                                                                                                    source = discord.FFmpegPCMAudio(file_name)
                                                                                                                                                                                                                                                                                            voice_client.play(source, after=after_playing)
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                print(f"Erro ao processar o TTS: {e}")
                                                                                                                                                                                                                                                                                                                        if os.path.exists(file_name):
                                                                                                                                                                                                                                                                                                                                    os.remove(file_name)
                                                                                                                                                                                                                                                                                                                                            await play_next(guild, voice_client)

                                                                                                                                                                                                                                                                                                                                            @bot.event
                                                                                                                                                                                                                                                                                                                                            async def on_ready():
                                                                                                                                                                                                                                                                                                                                                print(f'🤖 Bot TTS conectado com sucesso como {bot.user}')
                                                                                                                                                                                                                                                                                                                                                    print(f'Canal alvo configurado: {CANAL_TEXTO_ID}')

                                                                                                                                                                                                                                                                                                                                                    @bot.event
                                                                                                                                                                                                                                                                                                                                                    async def on_message(message):
                                                                                                                                                                                                                                                                                                                                                        if message.author.bot:
                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        await bot.process_commands(message)

                                                                                                                                                                                                                                                                                                                                                                            if message.channel.id != CANAL_TEXTO_ID:
                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                if message.content.startswith(bot.command_prefix):
                                                                                                                                                                                                                                                                                                                                                                                                        return

                                                                                                                                                                                                                                                                                                                                                                                                            text = message.content.strip()

                                                                                                                                                                                                                                                                                                                                                                                                                if len(text) > 250:
                                                                                                                                                                                                                                                                                                                                                                                                                        await message.add_reaction('❌')
                                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                            text = re.sub(r'http[s]?://\S+', '', text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                text = re.sub(r'<@!?&?\d+>', '', text)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        text = text.strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not text:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                voice_client = discord.utils.get(bot.voice_clients, guild=message.guild)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not voice_client or not voice_client.is_connected():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state = get_state(message.guild.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await state.queue.put((text, message.id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await message.add_reaction('✅')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not state.is_playing:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await play_next(message.guild, voice_client)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @bot.command(name='entrar')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def entrar(ctx):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not ctx.author.voice:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await ctx.send("⚠️ Você precisa estar em um canal de voz para me chamar!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                channel = ctx.author.voice.channel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    voice_client = discord.utils.get(bot.voice_clients, guild=ctx.guild)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if voice_client and voice_client.is_connected():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await voice_client.move_to(channel)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await channel.connect()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await ctx.send(f"🎙️ Conectado ao canal **{channel.name}**! Pode mandar texto no canal configurado.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @bot.command(name='sair')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def sair(ctx):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                voice_client = discord.utils.get(bot.voice_clients, guild=ctx.guild)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if voice_client and voice_client.is_connected():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state = get_state(ctx.guild.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while not state.queue.empty():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state.queue.get_nowait()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.is_playing = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        voice_client.stop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await voice_client.disconnect()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await ctx.send("🔌 Desconectado e fila de áudio esvaziada!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await ctx.send("⚠️ Eu não estou em nenhum canal de voz no momento.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @bot.command(name='pular')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def pular(ctx):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        voice_client = discord.utils.get(bot.voice_clients, guild=ctx.guild)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if voice_client and voice_client.is_playing():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        voice_client.stop()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await ctx.send("⏭️ Áudio pulado!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await ctx.send("⚠️ Não há nenhum áudio tocando no momento.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @bot.event
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def on_voice_state_update(member, before, after):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if member.id == bot.user.id:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    voice_client = member.guild.voice_client
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not voice_client:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state = get_state(member.guild.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        human_members = [m for m in voice_client.channel.members if not m.bot]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(human_members) == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if state.afk_task is None or state.afk_task.done():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                state.afk_task = bot.loop.create_task(afk_disconnect(member.guild, voice_client))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if state.afk_task and not state.afk_task.done():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.afk_task.cancel()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.afk_task = None

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def afk_disconnect(guild, voice_client):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await asyncio.sleep(180)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if voice_client.is_connected():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            state = get_state(guild.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while not state.queue.empty():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        state.queue.get_nowait()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    state.is_playing = False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await voice_client.disconnect()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"💤 Bot desconectado de {guild.name} por inatividade (AFK).")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except asyncio.CancelledError:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pass

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not TOKEN:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("ERRO: Token do bot não encontrado. Configure a variável TOKEN.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        keep_alive()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.run(TOKEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                